name: Actualizacion Diaria de Aulas

on:
  schedule:
    # Se ejecuta todos los días a las 06:00 AM (UTC)
    - cron: '0 6 * * *'
  workflow_dispatch: # Permite que tú lo lances a mano si quieres probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerias necesarias
        run: |
          pip install gspread google-auth pandas requests pytz

      - name: Ejecutar scripts
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          THINGSPEAK_READ_KEY: ${{ secrets.THINGSPEAK_READ_KEY }}
          THINGSPEAK_CHANNEL_ID: ${{ secrets.THINGSPEAK_CHANNEL_ID }} # <-- AQUÍ ESTÁ
        run: |
          python update_aulas_full.py
          python update_sensor_clima.py
